### ISSUE TITLE
Book Recommendation

### ISSUE THREAD

**Issue by tirthasheshpatel** [tirth-hihoriya/CPP_World#1]
I recommend you to read the following books if you are interested in learning c++:
1. [Accelarated C++](https://www.amazon.in/Accelerated-Practical-Programming-Addison-Wesley-Depth/dp/020170353X)
2. [A Tour of C++](https://www.amazon.in/Tour-C-Bjarne-Stroustrup/dp/9332555338)

Both the books are short, concise, dense and to-the-point.

**Comment by tirth-hihoriya** [comment]
Thank you for your concern.
I will definitely read those books.
